apiVersion: v1
kind: Service
metadata:
  name: mercado-livro-api-service
spec:
  type: LoadBalancer
  selector:
    app: mercado-livro-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
