name: Build, Push Docker Image and Deploy to AWS EKS

on:
  push:
    branches:
      - master

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1
      ECR_REPOSITORY: 395822550812.dkr.ecr.us-east-1.amazonaws.com/mercado-livro-api
      EKS_CLUSTER_NAME: mercado-livro-eks
      IMAGE_TAG: latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login no Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build a imagem Docker
        run: |
          docker build -t $ECR_REPOSITORY:$IMAGE_TAG .

      - name: Tag da imagem para ECR
        run: |
          IMAGE_URI="${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:$IMAGE_TAG"
          docker tag $ECR_REPOSITORY:$IMAGE_TAG $IMAGE_URI

      - name: Push da imagem para o ECR
        run: |
          IMAGE_URI="${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:$IMAGE_TAG"
          docker push $IMAGE_URI

      - name: Atualizar contexto do kubectl para EKS
        run: |
          aws eks update-kubeconfig --region $AWS_REGION --name $EKS_CLUSTER_NAME

      - name: Deploy no cluster EKS
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
