name: Docker Build & Push

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build da imagem
        run: |
          docker build -t danilodacosta/mercado-livro-api:latest .

      - name: Push para o Docker Hub
        run: |
          docker push danilodacosta/mercado-livro-api:latest
