name: Docker Build & Push

on:
  push:
    branches:
      - develop

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: mercado-livro
          file: mercado-livro/Dockerfile
          push: true
          tags: |
            danilodacosta/mercado-livro-api:${{ github.run_number }}
            danilodacosta/mercado-livro-api:latest
      #- name: Build da imagem
      #  run: |
      #    docker build -t danilodacosta/mercado-livro-api:latest .

      #- name: Push para o Docker Hub
      #  run: |
      #    docker push danilodacosta/mercado-livro-api:latest